create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  goal text not null default '',
  bio text not null default '',
  role text not null default 'mentee' check (role in ('mentee', 'mentor', 'admin')),
  avatar_url text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists profiles_phone_unique
  on public.profiles (phone)
  where phone <> '';

create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  service_type text not null,
  audience text not null default '',
  goal text not null,
  preferred_format text not null,
  preferred_channel text not null default '',
  preferred_time text not null default '',
  note text not null default '',
  status text not null default 'new',
  admin_note text not null default '',
  meeting_link text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mentor_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  expertise text not null,
  experience text not null default '',
  motivation text not null,
  portfolio_link text not null default '',
  status text not null default 'pending',
  admin_note text not null default '',
  activation_code text not null default '',
  invited_at timestamptz,
  activated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;
alter table public.consultation_requests enable row level security;
alter table public.mentor_applications enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);
