create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  goal text not null default '',
  bio text not null default '',
  role text not null default 'mentee' check (role in ('mentee', 'mentor', 'admin')),
  mentor_id text not null default '',
  avatar_url text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists profiles_phone_unique
  on public.profiles (phone)
  where phone <> '';

create unique index if not exists profiles_mentor_id_unique
  on public.profiles (mentor_id)
  where mentor_id <> '';

create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  service_type text not null,
  audience text not null default '',
  goal text not null,
  preferred_format text not null,
  preferred_channel text not null default '',
  preferred_time text not null default '',
  note text not null default '',
  status text not null default 'new',
  admin_note text not null default '',
  meeting_link text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mentor_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  expertise text not null,
  experience text not null default '',
  motivation text not null,
  portfolio_link text not null default '',
  status text not null default 'pending',
  admin_note text not null default '',
  activation_code text not null default '',
  invited_at timestamptz,
  activated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mentor_profile_updates (
  id text primary key,
  mentor_id text not null,
  mentor_user_id uuid references auth.users (id) on delete set null,
  mentor_name text not null,
  status text not null default 'pending',
  admin_note text not null default '',
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mentor_profiles (
  id text primary key,
  owner_user_id uuid references auth.users (id) on delete set null,
  email text not null default '',
  name text not null,
  field text not null default '',
  visibility text not null default 'draft',
  status text not null default 'pending',
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  mentor_id text not null,
  mentor_name text not null,
  mentor_image text not null default '',
  mentor_focus text not null default '',
  mentee_user_id uuid references auth.users (id) on delete set null,
  mentee_name text not null,
  mentee_email text not null,
  service_package_id text not null default '',
  service_name text not null,
  service_duration_minutes integer not null default 0,
  service_price_text text not null default '',
  proposed_options jsonb not null default '[]'::jsonb,
  slot_id text not null default '',
  slot_ids jsonb not null default '[]'::jsonb,
  goal text not null default '',
  preferred_time text not null default '',
  note text not null default '',
  status text not null default 'pending',
  admin_note text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

update public.consultation_requests
set status = 'new'
where status not in ('new', 'contacted', 'scheduled', 'completed');

update public.mentor_applications
set status = 'pending'
where status not in ('pending', 'interviewing', 'approved', 'rejected', 'activated');

update public.mentor_profile_updates
set status = 'pending'
where status not in ('pending', 'approved', 'rejected');

update public.mentor_profiles
set visibility = 'draft'
where visibility not in ('draft', 'public');

update public.mentor_profiles
set status = 'pending'
where status not in ('pending', 'approved', 'rejected', 'interviewing', 'activated');

update public.mentor_profiles
set visibility = 'draft'
where visibility = 'public' and status <> 'approved';

update public.booking_requests
set status = 'pending'
where status not in ('pending', 'accepted', 'rejected', 'completed');

alter table public.consultation_requests
  drop constraint if exists consultation_requests_status_check;
alter table public.consultation_requests
  add constraint consultation_requests_status_check
  check (status in ('new', 'contacted', 'scheduled', 'completed'));

alter table public.mentor_applications
  drop constraint if exists mentor_applications_status_check;
alter table public.mentor_applications
  add constraint mentor_applications_status_check
  check (status in ('pending', 'interviewing', 'approved', 'rejected', 'activated'));

alter table public.mentor_profile_updates
  drop constraint if exists mentor_profile_updates_status_check;
alter table public.mentor_profile_updates
  add constraint mentor_profile_updates_status_check
  check (status in ('pending', 'approved', 'rejected'));

alter table public.mentor_profiles
  drop constraint if exists mentor_profiles_visibility_check;
alter table public.mentor_profiles
  add constraint mentor_profiles_visibility_check
  check (visibility in ('draft', 'public'));

alter table public.mentor_profiles
  drop constraint if exists mentor_profiles_status_check;
alter table public.mentor_profiles
  add constraint mentor_profiles_status_check
  check (status in ('pending', 'approved', 'rejected', 'interviewing', 'activated'));

alter table public.mentor_profiles
  drop constraint if exists mentor_profiles_public_requires_approved_check;
alter table public.mentor_profiles
  add constraint mentor_profiles_public_requires_approved_check
  check (visibility <> 'public' or status = 'approved');

alter table public.booking_requests
  drop constraint if exists booking_requests_status_check;
alter table public.booking_requests
  add constraint booking_requests_status_check
  check (status in ('pending', 'accepted', 'rejected', 'completed'));

alter table public.profiles enable row level security;
alter table public.consultation_requests enable row level security;
alter table public.mentor_applications enable row level security;
alter table public.mentor_profile_updates enable row level security;
alter table public.mentor_profiles enable row level security;
alter table public.booking_requests enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);
